Broadly, there are three different types of derived metrics:



1.    Type-driven metrics

2.    Business-driven metrics

3.    Data-driven metrics





Type-Driven Metrics



These metrics can be derived by understanding the variable’s typology. You have already learnt one simple way of classifying variables/attributes — categorical (ordered, unordered) and quantitative or numeric. Similarly, there are various other ways of classification, one of which is Steven's typology.



Steven’s typology classifies variables into four types — nominal, ordinal, interval and ratio:

Nominal variables: Categorical variables, where the categories differ only by their names; there is no order among categories, e.g. colour (red, blue, green), gender (male, female), department (HR, analytics, sales)

These are the most basic form of categorical variables

Ordinal variables: Categories follow a certain order, but the mathematical difference between categories is not meaningful, e.g. education level (primary school, high school, college), height (high, medium, low), performance (bad, good, excellent), etc.

Ordinal variables are nominal as well

Interval variables: Categories follow a certain order, and the mathematical difference between categories is meaningful but division or multiplication is not, e.g. temperature in degrees celsius ( the difference between 40 and 30 degrees C is meaningful, but 30 degrees x 40 degrees is not), dates (the difference between two dates is the number of days between them, but 25th May / 5th June is meaningless), etc.

Interval variables are both nominal and ordinal

Ratio variables: Apart from the mathematical difference, the ratio (division/multiplication) is possible, e.g. sales in dollars ($100 is twice $50), marks of students (50 is half of 100), etc.

Ratio variables are nominal, ordinal and interval type

What is the difference between ordinal, interval and ratio variables? Why should I care?
In the 1940s, Stanley Smith Stevens introduced four scales of measurement: nominal, ordinal, interval, and ratio. These are still widely used today as a way to describe the characteristics of a variable. Knowing the scale of measurement for a variable is an important aspect in choosing the right statistical analysis.



Nominal
A nominal scale describes a variable with categories that do not have a natural order or ranking. You can code nominal variables with numbers if you want, but the order is arbitrary and any calculations, such as computing a mean, median, or standard deviation, would be meaningless.

Examples of nominal variables include:

genotype, blood type, zip code, gender, race, eye color, political party

Ordinal
An ordinal scale is one where the order matters but not the difference between values.

Examples of ordinal variables include:

socio economic status (“low income”,”middle income”,”high income”), education level (“high school”,”BS”,”MS”,”PhD”), income level (“less than 50K”, “50K-100K”, “over 100K”), satisfaction rating (“extremely dislike”, “dislike”, “neutral”, “like”, “extremely like”).

Note the differences between adjacent categories do not necessarily have the same meaning. For example, the difference between the two income levels “less than 50K” and “50K-100K” does not have the same meaning as the difference between the two income levels “50K-100K” and “over 100K”.

Make more informed and accurate analysis choices with Prism. Start your free Prism trial.

Interval
An interval scale is one where there is order and the difference between two values is meaningful.

Examples of interval variables include:

temperature (Farenheit), temperature (Celcius), pH, SAT score (200-800), credit score (300-850).

Ratio
A ratio variable, has all the properties of an interval variable, and also has a clear definition of 0.0. When the variable equals 0.0, there is none of that variable.

Examples of ratio variables include:

enzyme activity, dose amount, reaction rate, flow rate, concentration, pulse, weight, length, temperature in Kelvin (0.0 Kelvin really does mean “no heat”), survival time.

When working with ratio variables, but not interval variables, the ratio of two measurements has a meaningful interpretation. For example, because weight is a ratio variable, a weight of 4 grams is twice as heavy as a weight of 2 grams. However, a temperature of 10 degrees C should not be considered twice as hot as 5 degrees C. If it were, a conflict would be created because 10 degrees C is 50 degrees F and 5 degrees C is 41 degrees F. Clearly, 50 degrees is not twice 41 degrees.  Another example, a pH of 3 is not twice as acidic as a pH of 6, because pH is not a ratio variable.

 



Learn more about the difference between nominal, ordinal, interval and ratio data with this video by NurseKillam

 

 OK to compute....

Nominal

Ordinal

Interval

Ratio

 Frequency distribution

Yes

Yes

Yes

Yes

 Median and percentiles

No

Yes

Yes

Yes

 Add or subtract

No

No

Yes

Yes

 Mean, standard deviation, standard error of the mean 

No

No

Yes

Yes

 Ratios, coefficient of variation

No

No

No

Yes

 

Does measurement scale matter for data analysis? 
Knowing the measurement scale for your variables can help prevent mistakes like taking the average of a group of zip (postal) codes, or taking the ratio of two pH values. Beyond that, knowing the measurement scale for your variables doesn’t really help you plan your analyses or interpret the results.

Note that sometimes, the measurement scale for a variable is not clear cut. What kind of variable is color? In a psychological study of perception, different colors would be regarded as nominal. In a physics study, color is quantified by wavelength, so color would be considered a ratio variable. What about counts? 

There are occasions when you will have some control over the measurement scale. For example, with temperature, you can choose degrees C or F and have an interval scale or choose degrees Kelvin and have a ratio scale. With income level, instead of offering categories and having an ordinal scale, you can try to get the actual income and have a ratio scale. Generally speaking, you want to strive to have a scale towards the ratio end as opposed to the nominal end.

Save time performing statistical analysis with Prism. Try Prism for free.

Test your understanding of Nominal, Ordinal, Interval, and Ratio Scales
Each scale is represented once in the list below. 

Favorite candy bar
Weight of luggage
Year of your birth
Egg size (small, medium, large, extra large, jumbo)
Each scale is represented once in the list below. 

Military rank
Number of children in a family
Jersey numbers for a football team
Shoe size
Answers: N,R,I,O and O,R,N,I

 

Quantitative (Numerical) vs Qualitative (Categorical)
There are other ways of classifying variables that are common in statistics. One is qualitative vs. quantitative. Qualitative variables are descriptive/categorical. Many statistics, such as mean and standard deviation, do not make sense to compute with qualitative variables. Quantitative variables have numeric meaning, so statistics like means and standard deviations make sense. 




 

This type of classification can be important to know in order to choose the correct type of statistical analysis. For example, the choice between regression (quantitative X) and ANOVA (qualitative X) is based on knowing this type of classification for the X variable(s) in your analysis.

Quantitative variables can be further classified into Discrete and Continuous. Discrete variables can take on either a finite number of values, or an infinite, but countable number of values. The number of patients that have a reduced tumor size in response to a treatment is an example of a discrete random variable that can take on a finite number of values. The number of car accidents at an intersection is an example of a discrete random variable that can take on a countable infinite number of values (there is no fixed upper limit to the count).

Continuous variables can take on infinitely many values, such as blood pressure or body temperature. Even though the actual measurements might be rounded to the nearest whole number, in theory, there is some exact body temperature going out many decimal places That is what makes variables such as blood pressure and body temperature continuous. 

It is important to know whether you have a discrete or continuous variable when selecting a distribution to model your data. The Binomial and Poisson distributions are popular choices for discrete data while the Gaussian and Lognormal are popular choices for continuous data.

 

Test your understanding of Discrete vs Continuous
The list below contains 3 discrete variables and 3 continuous variables:

Number of emergency room patients
Blood pressure of a patient
Weight of a patient
Pulse for a patient
Emergency room wait time rounded to the nearest minute
Tumor size
Answers: d,c,c,d,d,c

Note, even though a variable may discrete, if the variable takes on enough different values, it is often treated as continuous. For example, most analysts would treat the number of heart beats per minute as continuous even though it is a count. The main benefit of treating a discrete variable with many different unique values as continuous is to assume the Gaussian distribution in an analysis.

o summarise, there are three types of derived metrics:

Type-driven
Business-driven 
Data-driven


Deriving metrics from the business perspective is not an easy task. It requires decent domain experience. Without understanding the domain correctly, deriving insights becomes difficult and prone to errors. 



Let's try out an exercise. You have been using the National Achievement Survey data set starting since EDA. In case you don't have the data set yet, you can download the National Achievement Survey from  this link to answer the questions in the next page.



So you learned how type-driven and business-driven metrics are created and used for deriving useful insights from existing variables. In the next lecture, you will learn about the third type of derived metrics - data-driven metrics.

In [69]:
import pandas as pd
odi=pd.read_csv("odi-batting.csv")
odi.head()
odi['Strike Rate'] = (odi['Runs'] / odi['Balls']) * 100
odi.head()

,Country,Player,Runs,MatchDate,Weekday,Ground,Versus,Balls,Strike Rate
0,Afghanistan,Mohammad Shahzad,118,16-02-2010,Tue,Sharjah CA Stadium,Canada,121,97.520661
1,Afghanistan,Mohammad Shahzad,110,01-09-2009,Tue,VRA Ground,Netherlands,111,99.099099
2,Afghanistan,Mohammad Shahzad,100,16-08-2010,Mon,Cambusdoon New Ground,Scotland,72,138.888889
3,Afghanistan,Mohammad Shahzad,82,10-07-2010,Sat,Hazelaarweg,Netherlands,108,75.925926
4,Afghanistan,Mohammad Shahzad,57,01-07-2010,Thu,Sportpark Westvliet,Canada,57,100.000000

In [79]:
odi_centuries=odi[odi["Runs"]>100]
max=odi_centuries["Strike Rate"].max()
odi_centuries_max=odi_centuries[odi_centuries["Strike Rate"]==max]
odi_centuries_max

,Country,Player,Runs,MatchDate,Weekday,Ground,Versus,Balls,Strike Rate
28157,Pakistan,Shahid Afridi,102,04-10-1996,Fri,Gymkhana Club Ground,Sri Lanka,40,255.0

In [63]:
number0fCenturies = odi_centuries.groupby(['Player']).agg(
    centuries=('Runs', 'count'),
).reset_index().sort_values(by='centuries', ascending=False)
number0fCenturies

                  Player  centuries
214   Sachin R Tendulkar         42
201      Ricky T Ponting         29
219  Sanath T Jayasuriya         28
234     Sourav C Ganguly         21
97    Herschelle H Gibbs         20
..                   ...        ...
188       Peter G Fulton          1
45     Clayton B Lambert          1
46         Clive H Lloyd          1
185         Owais A Shah          1
48        Colin A Ingram          1

[271 rows x 2 columns]

In [87]:
odi_centuries['Strike Rate'] = (odi_centuries['Runs'] / odi_centuries['Balls']) * 100

#In which year were the maximum number of centuries scored by Indian players?
odi_centuries_india=odi_centuries[odi_centuries["Country"]=="India"]
odi_centuries_india
odi_centuries_india['Year'] = pd.to_datetime(odi_centuries_india['MatchDate'], format='%d-%m-%Y').dt.year
odi_centuries_india.groupby(['Year']).agg(
    centuries=('Runs', 'count'),
).reset_index().sort_values(by='centuries', ascending=False)

C:\Users\Hp\AppData\Local\Temp\ipykernel_48760\3111936015.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  odi_centuries['Strike Rate'] = (odi_centuries['Runs'] / odi_centuries['Balls']) * 100
C:\Users\Hp\AppData\Local\Temp\ipykernel_48760\3111936015.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  odi_centuries_india['Year'] = pd.to_datetime(odi_centuries_india['MatchDate'], format='%d-%m-%Y').dt.year

    Year  centuries
14  1998         15
15  1999         14
25  2009         13
26  2010         12
21  2005         11
24  2008         10
19  2003          9
18  2002          9
16  2000          9
12  1996          7
20  2004          7
17  2001          7
27  2011          7
10  1994          7
13  1997          6
22  2006          4
23  2007          4
4   1988          4
3   1987          4
1   1984          3
6   1990          3
7   1991          2
5   1989          2
2   1986          2
11  1995          1
9   1993          1
8   1992          1
0   1983          1

In [61]:
odi_centu

C:\Users\Hp\AppData\Local\Temp\ipykernel_48760\3942730562.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  odi_centuries['Strike Rate'] = (odi_centuries['Runs'] / odi_centuries['Balls']) * 100

Derived Metrics
Derived metrics are calculated using raw data to provide deeper insights. These are classified into three types:

1) Type-Driven Metrics
These metrics are derived based on the nature of data or the type of calculations performed. They help in understanding different dimensions of data processing.

Examples:
Ratio Metrics: Conversion Rate = (Number of Conversions / Total Visitors) × 100
Aggregated Metrics: Average Response Time = Total Response Time / Number of Requests
Trend Metrics: Monthly Growth Rate = (Current Month Revenue - Previous Month Revenue) / Previous Month Revenue
Key Points for Revision:
✔ Focus on how data is structured and calculated
✔ Often used in performance analysis and optimization
✔ Includes ratio, aggregation, and trend-based metrics

2) Business-Driven Metrics
These metrics align with business objectives and help in decision-making. They are derived from operational and financial data.

Examples:
Customer Retention Rate = (Number of Customers at End of Period - New Customers Acquired) / Customers at Start of Period × 100
Revenue per User (ARPU) = Total Revenue / Total Users
Customer Acquisition Cost (CAC) = Total Marketing Spend / Number of New Customers
Key Points for Revision:
✔ Directly impact business goals and profitability
✔ Help in strategic planning and forecasting
✔ Used by leadership and management teams

3) Data-Driven Metrics
These metrics are derived using data science techniques, machine learning, and statistical analysis. They provide insights based on historical trends and predictive modeling.

Examples:
Churn Prediction Score = Probability of a customer leaving based on historical data
Anomaly Detection Rate = (Number of Detected Anomalies / Total Data Points) × 100
Recommendation Accuracy = (Correct Recommendations / Total Recommendations) × 100
Key Points for Revision:
✔ Requires data analytics and machine learning techniques
✔ Used for predictive insights and anomaly detection
✔ Helps in improving decision-making through automation

Quick Revision Table
Metric Type	Purpose	Example
Type-Driven	Focuses on data calculations	Conversion Rate, Average Response Time
Business-Driven	Aligns with business goals	Customer Retention Rate, Revenue per User
Data-Driven	Uses analytics & ML for insights	Churn Prediction Score, Anomaly Detection